version: '3'
services:
    # Application container
    php:
        build: .
        container_name: medium_clone_server
        volumes:
            - ../:/server/http
        ports:
            - "1111:1111"
        links:
            - postgres
            - db
        environment:
            DEBUG: 'true'
        command: php -S 0.0.0.0:80 -t public public/index.php

    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: app
    db:
       image: mysql:5.7
       restart: always
       environment:
         MYSQL_DATABASE: 'db'
         MYSQL_USER: 'user'
         MYSQL_PASSWORD: 'password'
         MYSQL_ROOT_PASSWORD: 'password'
       ports:
         - '5555:3306'

volumes:
    my-db: