version: '3'
services:
    # Application container
    php:
        build: .
        restart: always
        container_name: medium_clone_server
        volumes:
            - ../:/server/http
        ports:
            - "80:80"
        links:
            - postgres
        environment:
            DEBUG: 'true'
        command: php -S 0.0.0.0:80 -t public public/index.php

    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: app

volumes:
    my-db: